services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_NAME=ChatBTV
      - WEBUI_TITLE=ChatBTV
      - WEBUI_DESCRIPTION=ChatBTV - Sua plataforma de chat inteligente
      - WEBUI_META_TITLE=ChatBTV
      - WEBUI_META_DESCRIPTION=ChatBTV - Sua plataforma de chat inteligente
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

volumes:
  ollama:
  open-webui: